In [2]:
import numpy as np

In [3]:
#cria uma matriz unidimensional
mt = np.array([1,2,3,4,5])
print(mt)
print(type(mt))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
#mais de uma dimensao
mt = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mt)

#separando linhas ou colunas
l = mt[2,:]
print(l)

#mostra tamanho dimensoes
print(mt.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [11]:
zeros = np.zeros([4,3])
print(zeros) 
print("-------------")

ale = np.random.random((5))
print(ale)
print("--------------")

gnr = np.random.default_rng(1)
ale3= gnr.integers(10, size = (3,4))
print(ale3)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------
[0.99003025 0.84096438 0.42253869 0.15304184 0.83432122]
--------------
[[4 5 7 9]
 [0 1 8 9]
 [2 3 8 4]]


In [12]:
#unique remove repetições

j = np.array([11,12,11,13,12,14,11,15,14])
j = np.unique(j)
print(j)

[11 12 13 14 15]
